source :gemcutter

gem 'rails', :git => 'git://github.com/mattbeedle/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'haml'
gem 'inherited_resources'
gem 'warden'
gem 'devise', :git => 'git://github.com/plataformatec/devise.git', :branch => 'master'
gem 'mongoid', :git => 'http://github.com/durran/mongoid.git'
gem 'mongo'
gem 'mongo_ext'
gem 'bson_ext'
gem 'compass', :git => 'git://github.com/chriseppstein/compass.git'
gem 'uuid'
gem 'faker'
gem 'has_scope'
gem 'navvy'
#gem 'whenever'
gem 'chronic'
gem 'mail'
gem 'beanstalk-client'
gem 'will_paginate', '3.0.pre'
gem 'riddle'
gem 'smurf'
gem 'carrierwave', :git => 'git://github.com/jnicklas/carrierwave.git'
gem 'memcached'
gem 'mongo_session_store', :git => 'git://github.com/mattbeedle/mongo_session_store.git'
gem 'wirble'

group :test do
  gem 'pickle'
  gem 'capybara'#, :git => 'git://github.com/jnicklas/capybara.git'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'spork'
  gem 'launchy'
  gem 'machinist_mongo', :require => 'machinist/mongoid'
  gem 'autotest-rails', :require => 'autotest/rails'
  gem 'redgreen'
  gem 'fakeweb'
  gem 'mocha'
  gem 'faker'
  gem 'shoulda', :git => 'git://github.com/bmaddy/shoulda', :branch => 'rails3'
end
